spring.main.allow-circular-references: true


server:
  port: 3001

#spring:
#  application:
#    name: keycloakproject
#  main:
#    allow-circular-references: true

keycloak:
  realm: my_realm
  auth-server-url: http://localhost:8081/auth
  ssl-required: external
  resource: my_client
  credentials:
    secret:  C3oI2o36hiRKN5wVNmRLfxKKK3XJhiXS
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: INFO
    com.example.keycloak: DEBUG